# Generated by Django 2.1.5 on 2019-01-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='price',
        ),
    ]
